cp ./CBTM-361B-AX-cells-D1/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-361B-AX-cells-D1/
cp ./CBTM-364B-AX-cells-D3/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-364B-AX-cells-D3/
cp ./CBTM-364B-LV-cells-D3/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-364B-LV-cells-D3/
cp ./CBTM-364B-LA-cells-D3/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-364B-LA-cells-D3/
cp ./CBTM-364B-SP-cells-D3/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-364B-SP-cells-D3/
cp ./CBTM-364B-RV-cells-D3/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-364B-RV-cells-D3/
cp ./CBTM-386C-RV-cells-D4/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-386C-RV-cells-D4/
cp ./CBTM-386C-RA-cells-D4/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-386C-RA-cells-D4/
cp ./CBTM-386C-AX-cells-D4/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-386C-AX-cells-D4/
cp ./CBTM-386C-LV-cells-D4/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-386C-LV-cells-D4/
cp ./CBTM-386C-LA-cells-D4/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-386C-LA-cells-D4/
cp ./CBTM-386C-SP-cells-D4/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-386C-SP-cells-D4/
cp ./CBTM-390C-RA-cells-D5/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-390C-RA-cells-D5/
cp ./CBTM-390C-LV-cells-D5/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-390C-LV-cells-D5/
cp ./CBTM-390C-SP-cells-D5/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-390C-SP-cells-D5/
cp ./CBTM-390C-RV-cells-D5/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-390C-RV-cells-D5/
cp ./CBTM-390C-AX-cells-D5/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-390C-AX-cells-D5/
cp ./CBTM-390C-LA-cells-D5/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-390C-LA-cells-D5/
cp ./CBTM-417C-AX-cd45-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-AX-cd45-D6/
cp ./CBTM-417C-SP-cells-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-SP-cells-D6/
cp ./CBTM-417C-RV-cd45-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-RV-cd45-D6/
cp ./CBTM-417C-LV-cd45-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-LV-cd45-D6/
cp ./CBTM-417C-RA-cd45-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-RA-cd45-D6/
cp ./CBTM-417C-LA-cells-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-LA-cells-D6/
cp ./CBTM-417C-LV-cells-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-LV-cells-D6/
cp ./CBTM-417C-LA-cd45-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-LA-cd45-D6/
cp ./CBTM-417C-RA-cells-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-RA-cells-D6/
cp ./CBTM-417C-RV-cells-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-RV-cells-D6/
cp ./CBTM-417C-AX-cells-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-AX-cells-D6/
cp ./CBTM-417C-SP-cd45-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-SP-cd45-D6/
cp ./CBTM-423C-RA-cd45-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-RA-cd45-D7/
cp ./CBTM-423C-LV-cd45-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-LV-cd45-D7/
cp ./CBTM-423C-LV-cells-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-LV-cells-D7/
cp ./CBTM-423C-LA-cells-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-LA-cells-D7/
cp ./CBTM-423C-RA-cells-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-RA-cells-D7/
cp ./CBTM-423C-SP-cells-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-SP-cells-D7/
cp ./CBTM-423C-LA-cd45-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-LA-cd45-D7/
cp ./CBTM-423C-SP-cd45-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-SP-cd45-D7/
cp ./CBTM-423C-RV-cells-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-RV-cells-D7/
cp ./CBTM-423C-AX-cells-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-AX-cells-D7/
cp ./CBTM-423C-AX-cd45-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-AX-cd45-D7/
cp ./CBTM-423C-RV-cd45-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-RV-cd45-D7/
cp ./CBTM-473C-LV-cells-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-LV-cells-D11/
cp ./CBTM-473C-RV-cells-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-RV-cells-D11/
cp ./CBTM-473C-AX-cells-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-AX-cells-D11/
cp ./CBTM-473C-SP-cd45-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-SP-cd45-D11/
cp ./CBTM-473C-RA-cells-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-RA-cells-D11/
cp ./CBTM-473C-LA-cells-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-LA-cells-D11/
cp ./CBTM-473C-SP-cells-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-SP-cells-D11/
cp ./CBTM-473C-AX-cd45-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-AX-cd45-D11/
cp ./CBTM-473C-LA-cd45-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-LA-cd45-D11/
cp ./CBTM-473C-RV-cd45-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-RV-cd45-D11/
cp ./CBTM-473C-RA-cd45-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-RA-cd45-D11/
cp ./CBTM-473C-LV-cd45-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-LV-cd45-D11/
