cp ./CBTM-361B-AX-nuclei-D1/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-361B-AX-nuclei-D1/
cp ./CBTM-361B-RV-nuclei-D1/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-361B-RV-nuclei-D1/
cp ./CBTM-361B-LA-nuclei-D1/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-361B-LA-nuclei-D1/
cp ./CBTM-361B-LV-nuclei-D1/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-361B-LV-nuclei-D1/
cp ./CBTM-362C-SP-nuclei-D2/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-362C-SP-nuclei-D2/
cp ./CBTM-362C-RV-nuclei-D2/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-362C-RV-nuclei-D2/
cp ./CBTM-362C-LV-nuclei-D2/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-362C-LV-nuclei-D2/
cp ./CBTM-362C-AX-nuclei-D2/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-362C-AX-nuclei-D2/
cp ./CBTM-362C-RA-nuclei-D2/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-362C-RA-nuclei-D2/
cp ./CBTM-362C-LA-nuclei-D2/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-362C-LA-nuclei-D2/
cp ./CBTM-364B-RA-nuclei-D3/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-364B-RA-nuclei-D3/
cp ./CBTM-364B-SP-nuclei-D3/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-364B-SP-nuclei-D3/
cp ./CBTM-364B-AX-nuclei-D3/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-364B-AX-nuclei-D3/
cp ./CBTM-364B-LV-nuclei-D3/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-364B-LV-nuclei-D3/
cp ./CBTM-364B-RV-nuclei-D3/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-364B-RV-nuclei-D3/
cp ./CBTM-364B-LA-nuclei-D3/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-364B-LA-nuclei-D3/
cp ./CBTM-386C-RA-nuclei-D4/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-386C-RA-nuclei-D4/
cp ./CBTM-386C-LA-nuclei-D4/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-386C-LA-nuclei-D4/
cp ./CBTM-386C-SP-nuclei-D4/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-386C-SP-nuclei-D4/
cp ./CBTM-386C-RV-nuclei-D4/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-386C-RV-nuclei-D4/
cp ./CBTM-386C-AX-nuclei-D4/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-386C-AX-nuclei-D4/
cp ./CBTM-386C-LV-nuclei-D4/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-386C-LV-nuclei-D4/
cp ./CBTM-390C-RA-nuclei-D5/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-390C-RA-nuclei-D5/
cp ./CBTM-390C-SP-nuclei-D5/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-390C-SP-nuclei-D5/
cp ./CBTM-390C-RV-nuclei-D5/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-390C-RV-nuclei-D5/
cp ./CBTM-390C-LA-nuclei-D5/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-390C-LA-nuclei-D5/
cp ./CBTM-390C-LV-nuclei-D5/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-390C-LV-nuclei-D5/
cp ./CBTM-390C-AX-nuclei-D5/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-390C-AX-nuclei-D5/
cp ./CBTM-417C-RA-nuclei-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-RA-nuclei-D6/
cp ./CBTM-417C-SP-nuclei-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-SP-nuclei-D6/
cp ./CBTM-417C-RV-nuclei-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-RV-nuclei-D6/
cp ./CBTM-417C-AX-nuclei-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-AX-nuclei-D6/
cp ./CBTM-417C-LV-nuclei-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-LV-nuclei-D6/
cp ./CBTM-417C-LA-nuclei-D6/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-417C-LA-nuclei-D6/
cp ./CBTM-423C-LV-nuclei-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-LV-nuclei-D7/
cp ./CBTM-423C-LA-nuclei-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-LA-nuclei-D7/
cp ./CBTM-423C-AX-nuclei-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-AX-nuclei-D7/
cp ./CBTM-423C-SP-nuclei-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-SP-nuclei-D7/
cp ./CBTM-423C-RA-nuclei-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-RA-nuclei-D7/
cp ./CBTM-423C-RV-nuclei-D7/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-423C-RV-nuclei-D7/
cp ./CBTM-473C-RA-nuclei-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-RA-nuclei-D11/
cp ./CBTM-473C-LV-nuclei-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-LV-nuclei-D11/
cp ./CBTM-473C-AX-nuclei-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-AX-nuclei-D11/
cp ./CBTM-473C-LA-nuclei-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-LA-nuclei-D11/
cp ./CBTM-473C-RV-nuclei-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-RV-nuclei-D11/
cp ./CBTM-473C-SP-nuclei-D11/*Cardiomyocyte_fr.gtf ./Cardiomyocyte_count_matrix/CBTM-473C-SP-nuclei-D11/
